# yaml-language-server: $schema=https://raw.githubusercontent.com/basetenlabs/truss/main/truss/config.schema.json
model_name: qwen-model
python_version: py313
requirements_file: requirements.txt
resources:
  accelerator: null
  cpu: '1'
  memory: 2Gi
  use_gpu: false
